Repository BHoM/Robot_Toolkit, pull requests merged in 2019-09, with the labels that each got.

#255 Robot_Toolkit-#254-Support for read groups
  Robot_Adapter/Read/Elements/Groups.cs
  Robot_Adapter/Read/Read.cs
  Robot_Adapter/Robot_Adapter.csproj
Labels: good first issue, size:S, type:feature

#257 Support for pulling geometric line loads and contour loads
  Robot_Adapter/Read/Loads/Load.cs
  Robot_Adapter/Read/Read.cs
Labels: type:feature

#260 Fix for update bars crashing for null DesignProperties
  Robot_Adapter/Update/Bars.cs
Labels: severity:critical, type:bug

#258 Robot_Toolkit: Update AssemblyFileVersion to 2.4.0.0
  Robot_Adapter/Properties/AssemblyInfo.cs
  Robot_Engine/Properties/AssemblyInfo.cs
  Robot_oM/Properties/AssemblyInfo.cs
Labels: type:compliance

#262 Robot_Toolkit-#261-PullSeismicCombinationModalDisplacements
  Robot_Adapter/Read/Results/NodeDisplacement.cs
Labels: good first issue, size:XS, type:feature
