Repository BHoM/Robot_Toolkit, pull requests merged in 2019-07, with the labels that each got.

#236 Added github issue templates
  .github/ISSUE_TEMPLATE/api_changed.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/compliance.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/test_script.md
Labels: type:feature

#234 TryGetValue for extracting material when pulling bars
  Robot_Engine/Convert/FromRobot/Bar.cs
Labels: type:bug

#239 Robot_Toolkit: Update Panel Create - to initialize openings correctly
  Robot_Adapter/Create/Panels.cs
Labels: severity:medium, size:S, type:bug
